### ISSUE TITLE
error in “is_world” function in the JC_functions.py

### ISSUE THREAD

**Issue by caoths** [PedroLormendez/jcclass#2]
I've been reviewing the “is_world” function in the JC_functions.py file and I've noticed a potential issue that could affect its accuracy.

In the current implementation, the function returns True when both condition_east and condition_west are False. This implies that the dataset is considered to cover the whole globe even when it does not, which could be misleading.

Here's the relevant code snippet:

“if condition_west == condition_east:
    es_mundo = True”
Wouldn't it be more accurate to update this condition to:

“if condition_west and condition_east:
    es_mundo = True”
This way, es_mundo will only be set to True if both conditions are met, correctly indicating global coverage.

I look forward to hearing your thoughts on this matter.

**Comment by PedroLormendez** [comment]
Hi. Thanks for raising this issue. I have fixed this potential issue in the code and should be now tracked in the 0.0.4 version.
